services:
  first:
    container_name: first
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "first"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","third":"http://third:8081/gossip"}'
    ports:
      - "8081:8080"
      - "8181:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'

  second:
    container_name: second
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "second"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"first":"http://first:8081/gossip","third":"http://third:8081/gossip"}'
    ports:
      - "8082:8080"
      - "8182:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  

  third:
    container_name: third
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "third"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","first":"http://first:8081/gossip"}'
    ports:
      - "8083:8080"
      - "8183:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  