services:
  first:
    container_name: first
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "first"
      APP_ADDRESS: "http://first:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","third":"http://third:8081/gossip","for":"http://for:8081/gossip","fifth":"http://fifth:8081/gossip"}'
    ports:
      - "8081:8080"
      - "8181:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'

  second:
    container_name: second
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "second"
      APP_ADDRESS: "http://second:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"first":"http://first:8081/gossip","third":"http://third:8081/gossip","for":"http://for:8081/gossip","fifth":"http://fifth:8081/gossip"}'
    ports:
      - "8082:8080"
      - "8182:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  

  third:
    container_name: third
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "third"
      APP_ADDRESS: "http://third:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","first":"http://first:8081/gossip","for":"http://for:8081/gossip","fifth":"http://fifth:8081/gossip"}'
    ports:
      - "8083:8080"
      - "8183:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  

  for:
    container_name: for
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "for"
      APP_ADDRESS: "http://for:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","first":"http://first:8081/gossip","third":"http://third:8081/gossip","fifth":"http://fifth:8081/gossip"}'
    ports:
      - "8084:8080"
      - "8184:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  

  fifth:
    container_name: fifth
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "fifth"
      APP_ADDRESS: "http://fifth:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"second":"http://second:8081/gossip","first":"http://first:8081/gossip","third":"http://third:8081/gossip","for":"http://for:8081/gossip"}'
    ports:
      - "8085:8080"
      - "8185:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  

  manual:
    container_name: manual
    platform: linux/amd64
    build:
      context: .
    environment:
      APP_NAME: "manual"
      APP_ADDRESS: "http://manual:8081/gossip"
      HTTP_PORT: "8080"
      GOSSIP_PORT: "8081"
      SEEDNODES_NODES: '{"first":"http://first:8081/gossip"}'
    ports:
      - "8086:8080"
      - "8186:8081"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1Gb'
        reservations:
          cpus: '0.60'
          memory: '1Gb'  